### ISSUE TITLE
Error: batch_layout_detection() got multiple values for argument 'batch_size'

### ISSUE THREAD

**Issue by shubhamnehate** [VikParuchuri/tabled#23]
there seems to be an issue with the tabled batch sizes it keeps on giving the following error when tabled is called

Traceback (most recent call last):
  File "/usr/local/bin/tabled", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/extract.py", line 41, in main
    page_results = extract_tables(images, highres_images, text_lines, det_models, rec_models, skip_detection=skip_detection, detect_boxes=detect_cell_boxes)
  File "/usr/local/lib/python3.10/dist-packages/tabled/extract.py", line 21, in extract_tables
    table_imgs, table_bboxes, table_counts = detect_tables(images, highres_images, det_models)
  File "/usr/local/lib/python3.10/dist-packages/tabled/inference/detection.py", line 38, in detect_tables
    layout_predictions = batch_layout_detection(images, layout_model, layout_processor, line_predictions, batch_size=layout_batch_size)
TypeError: batch_layout_detection() got multiple values for argument 'batch_size'

**Comment by VikParuchuri** [comment]
Apologies, this was a bug with the latest release.  Fix will be out shortly.
