### ISSUE TITLE
utf-8 support

### ISSUE THREAD

**Issue by lloooo** [VikParuchuri/tabled#7]
When I processed a table picture with Chinese characters, I encountered the following error
```Traceback (most recent call last):
  File "C:\Users\llooo\.conda\envs\tabled\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\llooo\.conda\envs\tabled\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\llooo\.conda\envs\tabled\Scripts\tabled.exe\__main__.py", line 7, in <module>
  File "C:\Users\llooo\.conda\envs\tabled\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\llooo\.conda\envs\tabled\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\llooo\.conda\envs\tabled\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\llooo\.conda\envs\tabled\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\llooo\.conda\envs\tabled\lib\site-packages\extract.py", line 55, in main
    f.write(formatted_result)
UnicodeEncodeError: 'gbk' codec can't encode character '\u0640' in position 194: illegal multibyte sequence
```

**Comment by VikParuchuri** [comment]
Hi, it looks like utf-8 is not the default codec on your system.  Set the environment variable like `export PYTHONIOENCODING=utf8`
